export enum QueryDataKeys {
  CHAT_MESSAGES = "chat-messages",
  SEND_MESSAGE = "send-message",
  NOTIFICATION_GROUPS = "notification-groups",
  MY_LIST_CHAT = "my-list-chat",
  PRIVATE_AGENTS_MKL = "private-agents-marketplace",
  MY_BOT_DATA = "my-bot-data",
  MY_BOT_LIST = "my-bot-list",
  DELEGATE_PRIVATE_AGENT = "delegate-private-agent",
  AGENT_LIVE_VOLUME = "agent-live-volume",
  CLOSE_LIVE_CHAT = "close-live-chat",
  EXPAND_LIVE_CHAT = "expand-live-chat",
  USER_PUBLIC_DETAIL = "user-public-detail",
  PUBLIC_AGENTS_BY_OWNER = "public-agents-by-owner",
}
